menloresearch/cortex.llamacpp

.github/workflows/build.yml
.github/workflows/quality-gate.yml
Makefile
configure.bat
configure.sh

issue: https://github.com/janhq/cortex.llamacpp/issues/1

feat: pack libraries and  create releases

---

.github/workflows/build.yml

issue: https://github.com/janhq/cortex.llamacpp/issues/1

feat: push tag

---

src/LlamaEngine.cc
src/llama_server_context.h

Issue: https://github.com/janhq/cortex/issues/526

fix: cache fixup

---

src/LlamaEngine.cc
src/LlamaEngine.h

issue: https://github.com/janhq/jan/issues/2560

fix: finish_reason for non stream completion

---

src/llama_server_context.cc
src/llama_server_context.h

Release slot and send error if decode failed

fix: handle error if decode failed

---

.github/workflows/pr-remote.yml

Add CI auto create PR to update submodule

Add CI auto create PR to update submodule

---

.github/workflows/pr-remote.yml

Add trigger CI after create PR

Add trigger CI after create PR

---

.github/workflows/build.yml

Replace deprecated steps github action

Replace deprecated steps github action

---

.github/workflows/create-pr-sync-remote.yml
.github/workflows/pr-remote.yml

Chore fix auto sync

---

.github/scripts/e2e-test-server-linux-and-mac.sh
.github/scripts/e2e-test-server-windows.bat
base/cortex-common/enginei.h
examples/server/server.cc
src/llama_engine.cc
src/llama_engine.h

Issue: https://github.com/janhq/cortex.llamacpp/issues/33
Response example:
```
{
"data": [
{
"id": "nomic-embed-text-v1.5.f16",
"object": "model"
},
{
"id": "mistral-7b-instruct-v0.1.Q4_0",
"object": "model"
}
],
"object": "list"
}
```

feat: get running models

---

.github/workflows/create-pr-sync-remote.yml

Change cron job from Sunday to weekdays

chore: pr sync remote weekdays

---

src/llama_engine.cc

We only LOG_ERROR if has missing info in config. Should return false also.

fix: return false if error during loading model

---

src/llama_server_context.cc
src/llama_server_context.h

- Reduce lock scope
- Use atomic for gen_id

fix: small lock improvement

---

.github/workflows/build.yml
.github/workflows/quality-gate.yml
Makefile

Add codesign

---

.github/scripts/e2e-test-server.py
.github/workflows/quality-gate-submodule.yml
.github/workflows/quality-gate.yml

issue: https://github.com/janhq/cortex.llamacpp/issues/47

fix: use mistra model for submodule e2e

---

.github/runners/actions-runner-windows-cuda-11-7.dockerfile
.github/runners/actions-runner-windows-cuda-12-0.dockerfile
.github/workflows/build.yml
.github/workflows/quality-gate-submodule.yml
.github/workflows/quality-gate.yml
Makefile
third-party/CMakeLists.txt

Feature sccache for windows local

Feature sccache for windows local

---

.github/workflows/create-pr-sync-remote.yml
.github/workflows/nightly-build.yml
.github/workflows/nightly.yml
.github/workflows/quality-gate.yml

Add nightly Build CI

---

.github/workflows/nightly.yml

Change condition checking pr status

Change condition checking pr status

---

.github/workflows/nightly.yml

Correct script create tag

---

.github/workflows/nightly-build.yml

Use note auto-generate

---

src/llama_engine.cc
src/llama_utils.h

Currently we are using llama_model_path, add another option to specify the model path.

feat: add model_path parameter

---

.github/runners/actions-runner-ubuntu-cuda-11-7.dockerfile
.github/runners/actions-runner-ubuntu-cuda-12-0.dockerfile
.github/workflows/build.yml
.github/workflows/nightly-build.yml
.github/workflows/template-quality-gate-pr.yml
.github/workflows/template-quality-gate-submodule.yml
Makefile

Linux cuda separate cpu instruction and enable sccache

Linux cuda separate cpu instruction and enable sccache

---

.github/workflows/build.yml
.github/workflows/nightly-build.yml

add clean step

---

.github/workflows/build.yml
.github/workflows/nightly-build.yml
.github/workflows/template-quality-gate-pr.yml
.github/workflows/template-quality-gate-submodule.yml
README.md

fix: change llama build flags

---

Makefile

Add windows dependencies dll files

Add windows dependencies dll files

---

.github/workflows/build.yml
.github/workflows/nightly-build.yml
.github/workflows/template-quality-gate-pr.yml
.github/workflows/template-quality-gate-submodule.yml
src/llama_engine.cc
src/llama_server_context.cc

Issue: https://github.com/janhq/cortex/issues/647

fix: add embedding result info

---

.github/runners/actions-runner-ubuntu-cuda-12-0-ubuntu-2204.dockerfile
.github/workflows/build.yml
.github/workflows/nightly-build.yml
.github/workflows/template-quality-gate-pr.yml
.github/workflows/template-quality-gate-submodule.yml

Vulkan move to ubuntu 22.04

---

src/llama_server_context.cc

This PR updates the llama.cpp submodule to the latest release: b3534.

Update llama.cpp submodule to latest release b3534

---

.github/workflows/build.yml
.github/workflows/nightly-build.yml
.github/workflows/template-quality-gate-pr.yml
.github/workflows/template-quality-gate-submodule.yml

This PR updates the llama.cpp submodule to the latest release: b3567.

Update llama.cpp submodule to latest release b3567

---

.github/workflows/template-quality-gate-submodule.yml
src/llama_engine.cc
src/llama_server_context.cc

This PR updates the llama.cpp submodule to the latest release: b3658.

Update llama.cpp submodule to latest release b3658

---

examples/server/server.cc
src/llama_engine.cc

If we don't have configuration for logging, print to terminal with debug log level

fix: backward compatible logging

---

.github/workflows/build.yml
.github/workflows/nightly-build.yml
.github/workflows/template-quality-gate-pr.yml
.github/workflows/template-quality-gate-submodule.yml

This PR updates the llama.cpp submodule to the latest release: b3669.

Update llama.cpp submodule to latest release b3669

---

src/llama_client_slot.h
src/llama_server_context.cc
src/llama_server_context.h

This PR updates the llama.cpp submodule to the latest release: b3704.

Update llama.cpp submodule to latest release b3704

---

src/llama_server_context.cc

This PR updates the llama.cpp submodule to the latest release: b3720.

Update llama.cpp submodule to latest release b3720

---

base/cortex-common/enginei.h
src/llama_engine.cc
src/llama_engine.h
src/llama_server_context.cc
src/llama_server_context.h

This PR updates the llama.cpp submodule to the latest release: b3778.

Update llama.cpp submodule to latest release b3778

---

.github/workflows/build.yml
.github/workflows/nightly-build.yml
.github/workflows/template-quality-gate-pr.yml
.github/workflows/template-quality-gate-submodule.yml

Switch from sccache to ccache

---

.github/workflows/build.yml
.github/workflows/nightly-build.yml
.github/workflows/template-quality-gate-pr.yml
.github/workflows/template-quality-gate-submodule.yml
Makefile

sccache to ccache

---

.github/workflows/build.yml
.github/workflows/convert-model-all-quant.yml
.github/workflows/create-pr-sync-remote.yml
.github/workflows/nightly-build.yml
.github/workflows/nightly.yml
.github/workflows/template-e2e-weekend-test.yml
.github/workflows/template-quality-gate-pr.yml
.github/workflows/template-quality-gate-submodule.yml
.github/workflows/update-model-yml.yml
patches/0001-Add-API-query-buffer-size.patch
src/llama_engine.cc

Return VRAM usage from llamacpp. Only tested on Mac with unified memory.
Will need to test on other platform.

chore: return vram usage

---

src/llama_engine.cc

https://github.com/janhq/cortex.cpp/issues/1389
Screenshots:

fix: support chat completion content array type

---

.github/workflows/template-quality-gate-pr.yml
src/llama_engine.cc

fix: warm-up

---

src/llama_engine.cc
src/llama_engine.h

Should check nullptr before using a pointer

fix: check nullptr for async_file_logger_

---

src/chat_completion_request.h
src/llama_engine.cc
src/llama_server_context.cc

This PR updates the llama.cpp submodule to the latest release: b3989.

Update llama.cpp submodule to latest release b3989

---

src/chat_completion_request.h
src/llama_engine.cc

feat: support multiple choices

---

base/cortex-common/enginei.h
src/llama_engine.cc
src/llama_engine.h
src/llama_server_context.cc
src/llama_utils.h

Fix https://github.com/janhq/cortex.cpp/issues/1102

Add openai compatible embedding

---

src/llama_engine.cc

fix: unicode path windows

---

.github/workflows/nightly-build.yml
.github/workflows/nightly.yml

feat: nightly update llama.cpp use llama.cpp release name

feat: nightly update llama.cpp use llama.cpp release name

---

.github/workflows/build.yml
.github/workflows/nightly-build.yml
.github/workflows/nightly.yml

Fix codesign macos selfhosted 
Related issue: https://github.com/janhq/cortex.llamacpp/issues/322

Fix codesign macos selfhosted

---

.github/workflows/nightly-build.yml

chore: add remove keychain step ci

chore: add remove keychain step ci

---

.github/workflows/build.yml
.github/workflows/nightly-build.yml
.github/workflows/template-e2e-weekend-test.yml
.github/workflows/template-quality-gate-pr.yml
.github/workflows/template-quality-gate-submodule.yml

feat macos 12 arm64
- https://github.com/janhq/infra/issues/86

feat: macos 12 arm64

---

.github/workflows/template-quality-gate-submodule.yml

fix: ci nightly macos arm64

---

.github/runners/runner-trt-llm.ps1
.github/runners/start.sh

fix: ci auto install newest agent version

fix: ci auto install newest agent version

---

.github/workflows/build.yml
.github/workflows/nightly-build.yml
.github/workflows/template-e2e-weekend-test.yml
.github/workflows/template-quality-gate-pr.yml
.github/workflows/template-quality-gate-submodule.yml
src/llama_client_slot.cc
src/llama_server_context.cc

This PR updates the llama.cpp submodule to the latest release: b4397.

Update llama.cpp submodule to latest release b4397

---

patches/0001-Add-API-query-buffer-size.patch
src/llama_engine.cc
src/llama_server_context.cc
src/llama_server_context.h

This PR updates the llama.cpp submodule to the latest release: b4516.

Update llama.cpp submodule to latest release b4516

---

src/llama_engine.cc

This reverts commit e51e22c0122f706d445dad4c8198ab81c2e2e8c5.

Revert "fix: temporary disable warm up for deepseek-r1 (#379)"

---

.github/workflows/nightly.yml

fix: ci nightly

---

.github/workflows/create-pr-sync-remote.yml
.github/workflows/nightly.yml
.gitmodules
src/llama_server_context.cc

chore: update submodule url

---

.github/workflows/build.yml
.github/workflows/nightly-build.yml

chore: correct minio url

---

.github/workflows/build.yml
.github/workflows/nightly-build.yml
.github/workflows/template-e2e-weekend-test.yml
.github/workflows/template-quality-gate-pr.yml
.github/workflows/template-quality-gate-submodule.yml
CMakeLists.txt

This PR updates the llama.cpp submodule to the latest release: b5359.

Update llama.cpp submodule to latest release b5359
