menloresearch/cortex.llamacpp

.github/workflows/build.yml, examples/server/CMakeLists.txt, examples/server/dylib.h, examples/server/httplib.h, examples/server/server.cc, src/LlamaEngine.cc, third-party/CMakeLists.txt
issue: https://github.com/janhq/cortex.llamacpp/issues/2
=> feat: add server example

.github/scripts/e2e-test-server-linux-and-mac.sh, .github/scripts/e2e-test-server-windows.bat, .github/workflows/build.yml, examples/server/server.cc
Issues: 
- https://github.com/janhq/cortex.llamacpp/issues/4
- https://github.com/janhq/cortex.llamacpp/issues/3
=> feat: e2e testing for embedding and completion endpoints

.github/scripts/e2e-test-server-linux-and-mac.sh, .github/scripts/e2e-test-server-windows.bat, examples/server/server.cc, src/chat_completion_request.h, src/llama_engine.cc, src/llama_engine.h, src/llama_server_context.cc, src/llama_server_context.h, src/llama_utils.h
Issue link: https://github.com/janhq/cortex/issues/467
- use std::unordered_map to store all llama_server_context (lsc)
- refactor: move background thread to lsc, each lsc has its own background thread
We use mode_id as a key to find the model, so they have to be unique. That requires some changes in request parameter:
For completions:
Have to set value the model_alias for inferences/llamaCPP/loadmodel and inferences/llamaCPP/unloadmodel , this has to be the same as model parameter in inferences/llamaCPP/chat_completion
loadmodel/unloadmodel:
```
{
...
"llama_model_path": "file_to_location"
"model_alias": "model1"
...
}
```
chat_completion:
```
{
...
"model": "model1"  
...
}
```
For embeddings:
The same for loadmodel/unloadmodel, for embedding request, we need to add model parameter …
=> feat: multiple models

src/llama_engine.cc
In check model loaded, if we hit error, the loaded flag always be false
=> fix: print logic

README.md, src/llama_engine.cc
Configuration: To enable Flash Attention, need to add `flash_attn`: true to model.json
Tested on windows 11 4900 cuda 12, can see an improvement on token speed
Without Flash Attention:
```
llama_new_context_with_model: flash_attn = 0
20240522 06:33:42.958000 UTC 7864 DEBUG [PrintTimings] PrintTimings: prompt eval time = 284.746ms / 80 tokens (3.559325 ms per token, 280.952146826 tokens per second) - llama_client_slot.cc:79
20240522 06:33:42.958000 UTC 7864 DEBUG [PrintTimings] PrintTimings:        eval time = 32301.621 ms / 297 runs   (108.759666667 ms per token, 9.19458500241 tokens per second)
- llama_client_slot.cc:86
```
With Flash Attention:
```
llama_new_context_with_model: flash_attn = 1
20240522 06:31:41.109000 UTC 4872 DEBUG [PrintTimings] PrintTimings: prompt eval time = …
```
=> feat: support Flash Attention

README.md, src/llama_engine.cc
We are using `flash-attn` for Flash Attention parameter. Should use `flash_attn` for better json config convention.
=> fix: flash attention param typo

src/llama_engine.cc, src/llama_engine.h
Example:
```
{
"data": [
{
"id": "nomic-embed-text-v1.5.f16",
"engine": "cortex.llamacpp",
"start_time": 1716966123266, // Epoch time in miliseconds
"vram": "123", // MiB
"ram": "-", // For unknown 
"object": "model"
}
],
"object": "list"
}
```
We don't have VRAM and RAM yet. Will add it later.
=> feat: add more info on getting models

.github/workflows/build.yml, .github/workflows/quality-gate-submodule.yml, .github/workflows/quality-gate.yml
windows-latest after https://github.com/actions/runner-images/releases/tag/win22%2F20240603.1 has a bug that makes http server crashes.  
Use windows-2019 as runners for now.
=> chore: changes windows CI runners

src/llama_engine.cc, src/llama_server_context.cc
llava-1.6 needs more context than llava-1.5, at least 3000 is needed. Use 4096 for llava-1.6 context length
=> feat: request larger context for llava-v1.6

.github/scripts/e2e-test-server.py, src/llama_engine.cc, src/llama_server_context.cc
This PR updates the llama.cpp submodule to the latest release: b3197.
=> Update llama.cpp submodule to latest release b3197

src/llama_server_context.cc
This PR updates the llama.cpp submodule to the latest release: b3600.
=> Update llama.cpp submodule to latest release b3600

.github/workflows/build.yml, .github/workflows/nightly-build.yml, .github/workflows/template-e2e-weekend-test.yml, .github/workflows/template-quality-gate-pr.yml, .github/workflows/template-quality-gate-submodule.yml
We are using macos-13 for mac intel runner (not sure why)
Use macos-12 for now to support more mac OS version.
=> chore: use macos-12 instead of macos-13 for mac intel runner

src/chat_completion_request.h, src/llama_engine.cc, src/llama_server_context.cc
Fix https://github.com/janhq/cortex.cpp/issues/1151
=> feat: add llamacpp params

CMakeLists.txt, base/cortex-common/enginei.h, examples/server/server.cc, src/file_logger.cc, src/file_logger.h, src/llama_engine.cc, src/llama_engine.h
Fix https://github.com/janhq/cortex.cpp/issues/1054
Summary changed:
- Add `file_logger` implementation as `cortex-cpp` did
- Create an interface `SetFileLogger(int max_log_lines, const std::string& log_path)` so that when server in `cortex-cpp` load engines, it can enable file logger by calling this function
=> feat: redirect log

.github/workflows/build.yml, .github/workflows/nightly-build.yml, .github/workflows/template-quality-gate-pr.yml, .github/workflows/template-quality-gate-submodule.yml
Add version.txt add checksum for llamacpp engine
Related ticket: [#777](https://github.com/janhq/cortex.cpp/issues/777)
=> Add version.txt add checksum for llamacpp engine

.github/workflows/build.yml, .github/workflows/nightly-build.yml
package cuda dependencies to github release
Close: https://github.com/janhq/cortex.cpp/issues/1085
=> package cuda dependencies to github release

.github/runners/actions-runner-ubuntu-cuda-11-7.dockerfile, .github/runners/actions-runner-ubuntu-cuda-12-0-ubuntu-2204.dockerfile, .github/runners/actions-runner-ubuntu-cuda-12-0.dockerfile
Downgrade from gcc11 to gcc9 on ubuntu 20.04
Fix issue https://github.com/janhq/cortex.cpp/issues/1144
=> Downgrade from gcc11 to gcc9 on ubuntu 20.04

src/llama_utils.h
extractBase64 crashes on Debian Parrot. It seems like the same problem with https://gc.gnu.org/bugzilla.cgi?id=86164.
=> fix: proper way to extract base64

.github/workflows/build.yml, .github/workflows/nightly-build.yml, .github/workflows/template-e2e-weekend-test.yml, .github/workflows/template-quality-gate-pr.yml, .github/workflows/template-quality-gate-submodule.yml, src/chat_completion_request.h, src/llama_client_slot.cc, src/llama_client_slot.h, src/llama_engine.cc, src/llama_server_context.cc, src/llama_server_context.h
This PR updates the llama.cpp submodule to the latest release: b3943.
=> Update llama.cpp submodule to latest release b3943

src/chat_completion_request.h, src/llama_engine.cc
Example:
```
{
"choices": [],
"created": 1730108014,
"id": "whAQSseJhk2ZEf0cacOy",
"model": "_",
"object": "chat.completion.chunk",
"usage": {
"completion_tokens": 11,
"completion_tokens_details": {
"reasoning_tokens": 0
},
"prompt_tokens": 14,
"total_tokens": 25
}
}
```
Related issue: https://github.com/janhq/cortex.llamacpp/issues/265
=> feat: support stream_option for OpenAI API compatible

src/chat_completion_request.h, src/llama_engine.cc, src/llama_server_context.cc
Fix #262 
Can test this feature by use openai lib
```
from openai import OpenAI
ENDPOINT = "http://localhost:3928/v1"
MODEL = "meta-llama3.1-8b-instruct"
client = OpenAI(
base_url=ENDPOINT,
api_key="not-needed"
)
completion_payload = {
"messages": [
{"role": "user", "content": "Who won the world series in 2020?"}
]
}
response = client.chat.completions.create(
top_p=0.9,
temperature=0.6,
model=MODEL,
messages= completion_payload["messages"],
top_logprobs=2,
stream=False,
logprobs=True
)
print(response)
```
=> support OpenAI compatible log probs

patches/0001-Add-API-query-buffer-size.patch, src/llama_engine.cc
This PR updates the llama.cpp submodule to the latest release: b4079.
=> Update llama.cpp submodule to latest release b4079

src/chat_completion_request.h, src/llama_client_slot.h, src/llama_server_context.cc
This PR updates the llama.cpp submodule to the latest release: b4201.
=> Update llama.cpp submodule to latest release b4201

README.md, src/llama_engine.cc
This pull request includes changes to the `src/llama_engine.cc` file to improve code readability and add new parameters to the `LoadModelImpl` function. The most important changes are:
Code readability improvements:
* [`src/llama_engine.cc`](diffhunk://#diff-bca4ec26627d57d17c75e7c3d0f21accaf4c5b8e18eb2536ef2e3a6d3d32855bL273-R275): Reformatted the `kv_cache_types` vector to improve readability by aligning the elements in columns.
Functionality enhancements:
* [`src/llama_engine.cc`](diffhunk://#diff-bca4ec26627d57d17c75e7c3d0f21accaf4c5b8e18eb2536ef2e3a6d3d32855bR608): Added a new parameter `ctx_shift` to the `LoadModelImpl` function, with a default value of `true`. This parameter is extracted from the `json_body`.
Issue: https://github.com/janhq/cortex.cpp/issues/1843
=> fix: add ctx_shift parameter

src/llama_engine.cc
This pull request includes a change to the logging level in the `LlamaEngine::Load` method to provide more detailed debugging information.
Logging level change:
* [`src/llama_engine.cc`](diffhunk://#diff-bca4ec26627d57d17c75e7c3d0f21accaf4c5b8e18eb2536ef2e3a6d3d32855bL290-R290): Changed the logging level from `LOG_INFO` to `LOG_DEBUG` in the `LlamaEngine::Load` method to provide more detailed information during the engine loading process.
=> chore: down log level

patches/0001-Add-API-query-buffer-size.patch, src/llama_server_context.cc, src/llama_server_context.h
This PR updates the llama.cpp submodule to the latest release: b4453.
=> Update llama.cpp submodule to latest release b4453

.github/workflows/build.yml, .github/workflows/nightly-build.yml, .github/workflows/template-quality-gate-pr.yml, .github/workflows/template-quality-gate-submodule.yml
Related issue: https://github.com/janhq/cortex.cpp/issues/1855
This pull request includes updates to the CMake build flags in various GitHub workflow files to disable the `GGML_F16C` flag across multiple build configurations. 
Changes to GitHub workflow files:
* [`.github/workflows/build.yml`](diffhunk://#diff-5c3fa597431eda03ac3339ae6bf7f05e1a50d6fc7333679ec38e21b337cb6721L84-R84): Updated `cmake-flags` to include `-DGGML_F16C=OFF` for various Linux and Windows build configurations. [[1]](diffhunk://#diff-5c3fa597431eda03ac3339ae6bf7f05e1a50d6fc7333679ec38e21b337cb6721L84-R84) [[2]](diffhunk://#diff-5c3fa597431eda03ac3339ae6bf7f05e1a50d6fc7333679ec38e21b337cb6721L116-R116) [[3]](diffhunk://#diff-5c3fa597431eda03ac3339ae6bf7f05e1a50d6fc7333679ec38e21b337cb6721L148-R148) …
=> chore: disable GGML_F16C flag for noavx build

src/llama_engine.cc
This pull request includes changes to the `src/llama_engine.cc` file to handle specific model types and improve the inference process. The most important changes are:
Model handling improvements:
* [`src/llama_engine.cc`](diffhunk://#diff-bca4ec26627d57d17c75e7c3d0f21accaf4c5b8e18eb2536ef2e3a6d3d32855bR729-R732): Added a condition to skip the warm-up process for models with IDs containing "deepseek-r1".
Inference process enhancements:
* [`src/llama_engine.cc`](diffhunk://#diff-bca4ec26627d57d17c75e7c3d0f21accaf4c5b8e18eb2536ef2e3a6d3d32855bR851-R854): Modified the `HandleInferenceImpl` method to append a specific end-of-sentence marker for models with IDs containing "deepseek-r1" when the input role is "assistant".
=> fix: temporary disable warm up for deepseek-r1

.github/workflows/build.yml, .github/workflows/nightly-build.yml, .github/workflows/template-quality-gate-pr.yml, .github/workflows/template-quality-gate-submodule.yml
This pull request includes several updates to the GitHub Actions workflows to add new build configurations for `amd64-vulkan-noavx` on both Linux and Windows. The changes are applied across multiple workflow files to ensure consistent build settings and support for different environments.
Updates to GitHub Actions workflows:
* [`.github/workflows/build.yml`](diffhunk://#diff-5c3fa597431eda03ac3339ae6bf7f05e1a50d6fc7333679ec38e21b337cb6721R105-R112): Added a new job configuration for `amd64-vulkan-noavx` on Linux and Windows with specific CMake flags and settings. [[1]](diffhunk://#diff-5c3fa597431eda03ac3339ae6bf7f05e1a50d6fc7333679ec38e21b337cb6721R105-R112) [[2]](diffhunk://#diff-5c3fa597431eda03ac3339ae6bf7f05e1a50d6fc7333679ec38e21b337cb6721R233-R240)
* …
=> chore: support noavx for vulkan build

.github/workflows/build.yml, .github/workflows/nightly-build.yml, .github/workflows/template-quality-gate-pr.yml, .github/workflows/template-quality-gate-submodule.yml
This PR updates the llama.cpp submodule to the latest release: b4778.
=> Update llama.cpp submodule to latest release b4778

patches/0001-Add-API-query-buffer-size.patch
This PR updates the llama.cpp submodule to the latest release: b4963.
=> Update llama.cpp submodule to latest release b4963

.github/workflows/build.yml, .github/workflows/convert-model-all-quant.yml, .github/workflows/create-pr-sync-remote.yml, .github/workflows/nightly-build.yml, .github/workflows/nightly.yml, .github/workflows/template-e2e-weekend-test.yml, .github/workflows/template-quality-gate-pr.yml, .github/workflows/template-quality-gate-submodule.yml, .github/workflows/update-model-yml.yml, src/llama_engine.cc, src/llama_server_context.cc
This PR updates the llama.cpp submodule to the latest release: b5205.
=> Update llama.cpp submodule to latest release b5205
